// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApRzMursz4MAK5k5KWbHcrI7SnzVckjdg',
    appId: '1:159569089966:web:25053eb89d7d6bb4e7243f',
    messagingSenderId: '159569089966',
    projectId: 'drivingtest-c9372',
    authDomain: 'drivingtest-c9372.firebaseapp.com',
    storageBucket: 'drivingtest-c9372.appspot.com',
    measurementId: 'G-X760WMVBNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyWFDoW1iyvY5ql6cCpWThembKy0qutzg',
    appId: '1:159569089966:android:176773472e509a52e7243f',
    messagingSenderId: '159569089966',
    projectId: 'drivingtest-c9372',
    storageBucket: 'drivingtest-c9372.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1y_tXaaQH5iV-VBL5pl8FhxO1GZlFCrA',
    appId: '1:159569089966:ios:22a1ba05b5779fbae7243f',
    messagingSenderId: '159569089966',
    projectId: 'drivingtest-c9372',
    storageBucket: 'drivingtest-c9372.appspot.com',
    iosBundleId: 'de.kevindroll.nachhaltigesfahren',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1y_tXaaQH5iV-VBL5pl8FhxO1GZlFCrA',
    appId: '1:159569089966:ios:22a1ba05b5779fbae7243f',
    messagingSenderId: '159569089966',
    projectId: 'drivingtest-c9372',
    storageBucket: 'drivingtest-c9372.appspot.com',
    iosBundleId: 'de.kevindroll.nachhaltigesfahren',
  );
}
